//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 12:15:34 PM CEST 
//


package pl.lodz.p.it.uci.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tgsid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="systemOrganisationId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tgsid",
    "systemOrganisationId"
})
@XmlRootElement(name = "getTpUserInfo")
public class GetTpUserInfo {

    @XmlElement(required = true, nillable = true)
    protected String tgsid;
    @XmlElement(required = true, nillable = true)
    protected String systemOrganisationId;

    /**
     * Gets the value of the tgsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTgsid() {
        return tgsid;
    }

    /**
     * Sets the value of the tgsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTgsid(String value) {
        this.tgsid = value;
    }

    /**
     * Gets the value of the systemOrganisationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemOrganisationId() {
        return systemOrganisationId;
    }

    /**
     * Sets the value of the systemOrganisationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemOrganisationId(String value) {
        this.systemOrganisationId = value;
    }

}
