//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 12:15:34 PM CEST 
//


package pl.lodz.p.it.uci.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="getTpUserInfoReturn" type="{http://sign.zp.comarch.gov}TpUserInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTpUserInfoReturn"
})
@XmlRootElement(name = "getTpUserInfoResponse")
public class GetTpUserInfoResponse {

    @XmlElement(required = true, nillable = true)
    protected TpUserInfo getTpUserInfoReturn;

    /**
     * Gets the value of the getTpUserInfoReturn property.
     * 
     * @return
     *     possible object is
     *     {@link TpUserInfo }
     *     
     */
    public TpUserInfo getGetTpUserInfoReturn() {
        return getTpUserInfoReturn;
    }

    /**
     * Sets the value of the getTpUserInfoReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpUserInfo }
     *     
     */
    public void setGetTpUserInfoReturn(TpUserInfo value) {
        this.getTpUserInfoReturn = value;
    }

}
