//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 12:15:34 PM CEST 
//


package pl.lodz.p.it.uci.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.lodz.p.it.uci.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TpUserInfoException_QNAME = new QName("http://exception.userinfo.zp.epuap.gov.pl", "TpUserInfoException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.lodz.p.it.uci.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTpUserInfoResponse }
     * 
     */
    public GetTpUserInfoResponse createGetTpUserInfoResponse() {
        return new GetTpUserInfoResponse();
    }

    /**
     * Create an instance of {@link TpUserInfo }
     * 
     */
    public TpUserInfo createTpUserInfo() {
        return new TpUserInfo();
    }

    /**
     * Create an instance of {@link GetTpUserInfo }
     * 
     */
    public GetTpUserInfo createGetTpUserInfo() {
        return new GetTpUserInfo();
    }

    /**
     * Create an instance of {@link TpUserInfoException }
     * 
     */
    public TpUserInfoException createTpUserInfoException() {
        return new TpUserInfoException();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TpUserInfoException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TpUserInfoException }{@code >}
     */
    @XmlElementDecl(namespace = "http://exception.userinfo.zp.epuap.gov.pl", name = "TpUserInfoException")
    public JAXBElement<TpUserInfoException> createTpUserInfoException(TpUserInfoException value) {
        return new JAXBElement<TpUserInfoException>(_TpUserInfoException_QNAME, TpUserInfoException.class, null, value);
    }

}
