//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 08:12:05 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://verification.zp.epuap.gov.pl")
package pl.lodz.p.it.uci.wsdl;
