//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 12:15:34 PM CEST 
//


package pl.lodz.p.it.uci.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TpUserInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TpUserInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="claimedRole" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TpUserInfo", namespace = "http://sign.zp.comarch.gov", propOrder = {
    "accountEmailAddress",
    "claimedRole"
})
public class TpUserInfo {

    @XmlElement(required = true, nillable = true)
    protected String accountEmailAddress;
    @XmlElement(required = true, nillable = true)
    protected String claimedRole;

    /**
     * Gets the value of the accountEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountEmailAddress() {
        return accountEmailAddress;
    }

    /**
     * Sets the value of the accountEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountEmailAddress(String value) {
        this.accountEmailAddress = value;
    }

    /**
     * Gets the value of the claimedRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimedRole() {
        return claimedRole;
    }

    /**
     * Sets the value of the claimedRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimedRole(String value) {
        this.claimedRole = value;
    }

}
